_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.10
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
experiment:
    value:
        name: experiment_chamfer_2025-02-11:16-01-35
        run: chamfer_20250211_160135
training:
    value:
        batch_size: 32
        clip_grad_norm: 1
        device: cuda
        dim_encoder: 2
        dim_hidden: 128
        dim_particles: 4
        eval_freq: 1000
        keep_last_n_checkpoints: 5
        learning_rate: 0.001
        log_freq: 100
        loss_type: chamfer
        min_lr: 1e-06
        num_encodings: 8
        num_epochs: 100
        num_heads: 4
        num_inds: 32
        num_particles: 500
        num_workers: 4
        save_freq: 5000
        scheduler_type: cosine
        sinkhorn_blur: 0.5
        sinkhorn_scaling: 0.5
        use_layer_norm: true
        warmup_epochs: 10
        weight_decay: 0
